### ISSUE TITLE
menu item link multiplication (菜单项链接乘法) (all google translate :))

### ISSUE THREAD

**Issue by mirfut** [1esse/vue-clownfish-admin-elem#1]
The first time you launch the application, the menu item link looks like this:
第一次启动应用程序时，菜单项链接如下所示：
[模态框](https://1esse.github.io/vue-clownfish-admin-elem/#/modal/index)

After closing the menu:
关闭菜单后：
[模态框](https://1esse.github.io/vue-clownfish-admin-elem/#/modal/modal/index)

After 4 closing the menu:)
4 后关闭菜单:)
https://1esse.github.io/vue-clownfish-admin-elem/#/modal/modal/modal/modal/modal/modal/modal/modal/index
![Screen Shot 2022-06-25 at 13 20 20 PM](https://user-images.githubusercontent.com/5353052/175769503-c8fd9d1b-8a40-4c3e-b9bb-67b4a68f6860.png)

**Comment by 1esse** [comment]
v1.0.8 bug fixed

**Comment by mirfut** [comment]
非常感谢您
之前它是如何正常工作的 [vue-clownfish-admin](https://github.com/1esse/vue-clownfish-admin) ?

**Comment by 1esse** [comment]
> 非常感谢您 之前它是如何正常工作的 [vue-clownfish-admin](https://github.com/1esse/vue-clownfish-admin) ?

这个bug会在手机端环境下触发，之前是一直存在的（之前不会触发因为没有适配手机端）。因为之前父路由只有一个子路由的时候会直接修改子路由的path，导致每次打开菜单都会修改一次path。可以对比现在和之前Sidebar.vue的函数getOnlyChildPath的代码。:)

**Comment by mirfut** [comment]
> 这个bug会在手机端环境下触发，之前是一直存在的（之前不会触发因为没有适配手机端）。因为之前父路由只有一个子路由的时候会直接修改子路由的path，导致每次打开菜单都会修改一次path。可以对比现在和之前Sidebar.vue的函数getOnlyChildPath的代码。:)

明白了，非常感谢您的回答。
我为。。。道歉 google translate :)

**Comment by 1esse** [comment]
> > 这个bug会在手机端环境下触发，之前是一直存在的（之前不会触发因为没有适配手机端）。因为之前父路由只有一个子路由的时候会直接修改子路由的path，导致每次打开菜单都会修改一次path。可以对比现在和之前Sidebar.vue的函数getOnlyChildPath的代码。:)
> 
> 明白了，非常感谢您的回答。 我为。。。道歉 google translate :)

thank you too, now the bug fixed.
